### ISSUE TITLE
No files generated under devel_prjs folder

### ISSUE THREAD

**Issue by mahdi-moradmand** [TripRichert/viv-prj-gen#2]
Hello There,

Hope you are well
I have a problem to used "the make blinky_genvivprj"
It seems it works properly and it start and finish but there is no files under the devel_prjs/ directory? and it seems it didn't generate Xilinx xpr project file.

Any idea?

.

**Comment by TripRichert** [comment]
I'm no longer developing on this project.  I think that there are better approaches to the way I wrote this

That said, I don't want this project to be broken, and I will try to figure out your problem and fix it.

are you running step 5 of the tutorial?  5-vivado-prj-generation ?

It works on my machine.  Can you post the vivado.log file that vivado generates in the build folder?  That might provide more information than the output from make.

What version of vivado are you using?  What OS are you using?

**Comment by mahdi-moradmand** [comment]
Thank you so much to back to me soon.
Vivado.log

#-----------------------------------------------------------
# Vivado v2017.4 (64-bit)
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
# Start of session at: Thu Feb 24 08:38:08 2022
# Process ID: 438102
# Current directory: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build
# Command line: vivado -mode gui -source -tclargs -prjname blinky -partname xc7k70tfbg484-3 -vhdl08synthfiles -vhdl08simfiles -verilogsynthfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/hdl/blinky_zedboard_z7.v -verilogsimfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/tb/blinky_tb.v -systemverilogsynthfiles -systemverilogsimfiles -xcifiles -unscopedearlyconstraints -unscopednormalconstraints -unscopedlateconstraints /project/codasip/mmoradmand/test/cmake_test/vivado_test/constraints/blinky_zedboard.xdc -scopedearlyconstraints -scopednormalconstraints -scopedlateconstraints -datafiles -builddir /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/xc7k70tfbg484-3/devel_prjs
# Log file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.log
# Journal file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.jou
#-----------------------------------------------------------
start_gui
exit
INFO: [Common 17-206] Exiting Vivado at Thu Feb 24 08:39:12 2022...

The Vivado is 2017.4 (64-bit) and the OS is CentOS Linux
and what I did: in 5-vivado-prj-generation I cmake and afterward make make blinky_genvivprj !

**Comment by TripRichert** [comment]
To confirm that this is the problem, can you put the line

message(STATUS "genvivprjscript is ${genvivprjscript}")

immediately after file(GLOB genvivprjscript "${CMAKE_CURRENT_LIST_DIR}/tcl/gen_prj.tcl")

in vivgen_functions.cmake

(I think this is line 7) and rerun cmake from your build directory

I get "-- genvivprjscript is /home/trip/Documents/viv-prj-gen/tcl/gen_prj.tcl"

**Comment by mahdi-moradmand** [comment]
I did change as you said:

```
#see copyright notice(s) at bottom of file

include(CMakeParseArguments)

# tcl script for generating vivado projects
file(GLOB genvivprjscript "${CMAKE_CURRENT_LIST_DIR}/tcl/gen_prj.tcl")
message(STATUS "genvivprjscript is ${genvivprjscript}")

#file used to parse commandline arguments
file(GLOB cmdlinedictprocsscript "${CMAKE_CURRENT_LIST_DIR}/tcl/tcl_utils/cmdline_dict.tcl")

function(add_vivado_devel_project)
```

This is what I see in terminal:
```
[mmoradmand@eng-08 build]$ cmake ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- genvivprjscript is 
-- Configuring done
-- Generating done
-- Build files have been written to: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build
[mmoradmand@eng-08 build]$ make blinky_genvivprj

****** Vivado v2017.4 (64-bit)
  **** SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
  **** IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
    ** Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.

INFO: [Common 17-206] Exiting Vivado at Thu Feb 24 09:48:26 2022...
Built target blinky_genvivprj
[mmoradmand@eng-08 build]$ 
```

And this is the log file:
```
#-----------------------------------------------------------
# Vivado v2017.4 (64-bit)
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
# Start of session at: Thu Feb 24 09:48:10 2022
# Process ID: 441120
# Current directory: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build
# Command line: vivado -mode batch -source -tclargs -prjname blinky -partname xc7k70tfbg484-3 -vhdl08synthfiles -vhdl08simfiles -verilogsynthfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/hdl/blinky_zedboard_z7.v -verilogsimfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/tb/blinky_tb.v -systemverilogsynthfiles -systemverilogsimfiles -xcifiles -unscopedearlyconstraints -unscopednormalconstraints -unscopedlateconstraints /project/codasip/mmoradmand/test/cmake_test/vivado_test/constraints/blinky_zedboard.xdc -scopedearlyconstraints -scopednormalconstraints -scopedlateconstraints -datafiles -builddir /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/xc7k70tfbg484-3/devel_prjs
# Log file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.log
# Journal file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.jou
#-----------------------------------------------------------
INFO: [Common 17-206] Exiting Vivado at Thu Feb 24 09:48:26 2022...
```

**Comment by TripRichert** [comment]
yeah, that shows that it isn't finding the file.

(after this comment, won't get back to you until this evening, have to go to my job)

what version of cmake are you using?

cmake --version

**Comment by mahdi-moradmand** [comment]
cmake version 3.22.1
Have a great day buddy

**Comment by TripRichert** [comment]
replace

message(STATUS "genvivprjscript is ${genvivprjscript}")

with

message(STATUS "genvivprjscript should be ${CMAKE_CURRENT_LIST_DIR}/tcl/gen_prj.tcl")

where is it looking for that file, and is the script there?

my guess is something is different about your directory structure.  The only other thing I can think of is file permissions, but I don't know how that would get messed up.

**Comment by mahdi-moradmand** [comment]
The same

```
[mmoradmand@eng-08 build]$ cmake ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- genvivprjscript should be /project/codasip/mmoradmand/test/cmake_test/vivado_test/cmake_utils/tcl/gen_prj.tcl
-- Configuring done
-- Generating done
-- Build files have been written to: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build
[mmoradmand@eng-08 build]$ make blinky_genvivprj

****** Vivado v2017.4 (64-bit)
  **** SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
  **** IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
    ** Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.

INFO: [Common 17-206] Exiting Vivado at Thu Feb 24 19:26:33 2022...
Built target blinky_genvivprj
[mmoradmand@eng-08 build]$ 
```

And the log file is:

```
#-----------------------------------------------------------
# Vivado v2017.4 (64-bit)
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
# Start of session at: Thu Feb 24 19:26:18 2022
# Process ID: 494336
# Current directory: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build
# Command line: vivado -mode batch -source -tclargs -prjname blinky -partname xc7k70tfbg484-3 -vhdl08synthfiles -vhdl08simfiles -verilogsynthfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/hdl/blinky_zedboard_z7.v -verilogsimfiles /project/codasip/mmoradmand/test/cmake_test/vivado_test/tb/blinky_tb.v -systemverilogsynthfiles -systemverilogsimfiles -xcifiles -unscopedearlyconstraints -unscopednormalconstraints -unscopedlateconstraints /project/codasip/mmoradmand/test/cmake_test/vivado_test/constraints/blinky_zedboard.xdc -scopedearlyconstraints -scopednormalconstraints -scopedlateconstraints -datafiles -builddir /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/xc7k70tfbg484-3/devel_prjs
# Log file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.log
# Journal file: /project/codasip/mmoradmand/test/cmake_test/vivado_test/build/vivado.jou
#-----------------------------------------------------------
INFO: [Common 17-206] Exiting Vivado at Thu Feb 24 19:26:33 20
```22...

> my guess is something is different about your directory structure. The only other thing I can think of is file permissions, but I don't know how that would get messed up.

I thought like you and because I moved vivgen_functions.cmake and the other .cmake in the same directory and just changed the address in top CMakeLists.txt, and moved them back and tested, but no change,

**Comment by TripRichert** [comment]
vivgen_functions.cmake assumes a relative path to the script tcl/gen_prj.tcl (relative path from vivgen_functions.cmake, not your cmakelists.txt file).

by moving stuff around, you've violated that assumption.

when vivgen_functions.cmake is included, vivgen_functions.cmake looks for tcl/gen_prj.tcl (from the locations of vivgen_functions.cmake) and, if it exists, stores the absolute path to gen_prj.tcl in the variable genvivprjscript in the scope that the file is included.  That variable is then used in the call to add_vivado_devel_project when you call that function from that same scope.

you need to move vivgen_functions.cmake to a location with a relative path of tcl/gen_prj.tcl to the gen_prj.tcl script.

In the output from your run,

-- genvivprjscript should be /project/codasip/mmoradmand/test/cmake_test/vivado_test/cmake_utils/tcl/gen_prj.tcl

demonstrates the problem.  cmake is looking in cmake_utils for the tcl/gen_prj.tcl .  That's not where the tcl folder and that script is.

**Comment by mahdi-moradmand** [comment]
Hey There,

I found it.
I missed the tcl folder :) 
By the way I believe it was better message missing tcl's/tcl folder.

Thank you so much again

**Comment by TripRichert** [comment]
I'm glad you figured it out.  Good luck with your stuff :)
